export enum EventType {
  TENANT_CREATED = 'tenant.created',
  AUTHENTICATION_USER_PROVISIONED = 'authentication.user-provisioned',
  EMPLOYEE_SUSPENDED = 'employee.suspended',
  EMPLOYEE_TERMINATED = 'employee.terminated',
  EMPLOYEE_REACTIVATED = 'employee.reactivated',
  AUTHENTICATION_SESSIONS_REVOKED = 'authentication.sessions-revoked',
  AUTHENTICATION_USER_INVITED = 'authentication.user-invited',
  AUTHENTICATION_INVITATION_ACCEPTED = 'authentication.invitation-accepted',
  AUTHENTICATION_INVITATION_RESENT = 'authentication.invitation-resent',
  AUTHENTICATION_PASSWORD_CHANGED = 'authentication.password-changed',
  AUTHORIZATION_ROLE_UPDATED = 'authorization.role-updated',
  ROLE_RENAMED = 'role.renamed',
  ROLE_PERMISSIONS_UPDATED = 'role.permissions-updated',
  ROLE_PROTECTED_CAPABILITY_VIOLATION = 'role.protected-capability-violation',
}
