export enum EventType {
  TENANT_CREATED = 'tenant.created',
  AUTHENTICATION_USER_PROVISIONED = 'authentication.user-provisioned',
  EMPLOYEE_SUSPENDED = 'employee.suspended',
  EMPLOYEE_TERMINATED = 'employee.terminated',
  EMPLOYEE_REACTIVATED = 'employee.reactivated',
  AUTHENTICATION_SESSIONS_REVOKED = 'authentication.sessions-revoked',
  AUTHENTICATION_USER_INVITED = 'authentication.user-invited',
  AUTHENTICATION_INVITATION_ACCEPTED = 'authentication.invitation-accepted',
  AUTHENTICATION_INVITATION_RESENT = 'authentication.invitation-resent',
  AUTHENTICATION_PASSWORD_CHANGED = 'authentication.password-changed',
  AUTHORIZATION_ROLE_UPDATED = 'authorization.role-updated',
  ROLE_CREATED = 'role.created',
  ROLE_COPIED = 'role.copied',
  ROLE_DEACTIVATED = 'role.deactivated',
  ROLE_REACTIVATED = 'role.reactivated',
  ROLE_RENAMED = 'role.renamed',
  ROLE_PERMISSIONS_UPDATED = 'role.permissions-updated',
  ROLE_PROTECTED_CAPABILITY_VIOLATION = 'role.protected-capability-violation',
  USER_GROUP_CREATED = 'user_group.created',
  USER_GROUP_UPDATED = 'user_group.updated',
  USER_GROUP_DEACTIVATED = 'user_group.deactivated',
  USER_GROUP_REACTIVATED = 'user_group.reactivated',
  USER_GROUP_ROLES_ASSIGNED = 'user_group.roles_assigned',
  USER_GROUP_ROLE_UNASSIGNED = 'user_group.role_unassigned',
  USER_GROUP_SCOPE_UPDATED = 'user_group.scope_updated',
  AUTHORIZATION_USER_GROUP_UPDATED = 'authorization.user-group-updated',
}
