export enum TableName {
  AUTH_SECURITY_EVENTS_OUTBOX = 'auth_security_events_outbox',
  CREDENTIALS = 'credentials',
  EXTERNAL_IDENTITIES = 'external_identities',
  EMPLOYEE_REFERENCES = 'employee_references',
  INVITATIONS = 'invitations',
  MFA_METHODS = 'mfa_methods',
  KAFKA_CONSUMED_EVENTS = 'kafka_consumed_events',
  AUTHENTICATION_SETTINGS = 'authentication_settings',
  TENANTS = 'tenants',
  USERS = 'users',
  ROLES = 'roles',
  ROLE_PERMISSIONS = 'role_permissions',
  USER_GROUPS = 'user_groups',
  USER_GROUP_ROLES = 'user_group_roles',
  USER_GROUP_MEMBERSHIPS = 'user_group_memberships',
  USER_EFFECTIVE_ROLES = 'user_effective_roles',
  AUTHORIZATION_SYNC_JOBS = 'authorization_sync_jobs',
}
