/**
 * AUTOGENERATED PERMISSION CONTRACTS - DO NOT EDIT MANUALLY
 * Generated from permission-catalog.yaml
 */

export const PermissionCodes = {
  LOCATION_VIEW: 'location.view',
  LOCATION_CREATE: 'location.create',
  LOCATION_UPDATE: 'location.update',
  LOCATION_DEACTIVATE: 'location.deactivate',
  LOCATION_DELETE: 'location.delete',
  EMPLOYEE_VIEW: 'employee.view',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_ARCHIVE: 'employee.archive',
  ROLE_VIEW: 'role.view',
  ROLE_CREATE: 'role.create',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  LEAVE_VIEW: 'leave.view',
  LEAVE_REQUEST: 'leave.request',
  LEAVE_APPROVE: 'leave.approve',
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_RUN: 'payroll.run',
} as const;

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes];

export const PlatformModules = [
  'setting',
  'directory',
  'authorization',
  'leave',
  'payroll',
] as const;
export type PlatformModule = (typeof PlatformModules)[number];

export interface PermissionMetadata {
  readonly id: PermissionCode;
  readonly module: PlatformModule;
  readonly resource: string;
  readonly action: string;
  readonly entry?: boolean;
  readonly deprecated?: boolean;
}

export const PERMISSION_METADATA_LIST: readonly PermissionMetadata[] = [
  {
    id: 'location.view',
    module: 'setting',
    resource: 'location',
    action: 'view',
    entry: true,
  },
  {
    id: 'location.create',
    module: 'setting',
    resource: 'location',
    action: 'create',
  },
  {
    id: 'location.update',
    module: 'setting',
    resource: 'location',
    action: 'update',
  },
  {
    id: 'location.deactivate',
    module: 'setting',
    resource: 'location',
    action: 'deactivate',
  },
  {
    id: 'location.delete',
    module: 'setting',
    resource: 'location',
    action: 'delete',
  },
  {
    id: 'employee.view',
    module: 'directory',
    resource: 'employee',
    action: 'view',
    entry: true,
  },
  {
    id: 'employee.create',
    module: 'directory',
    resource: 'employee',
    action: 'create',
  },
  {
    id: 'employee.update',
    module: 'directory',
    resource: 'employee',
    action: 'update',
  },
  {
    id: 'employee.archive',
    module: 'directory',
    resource: 'employee',
    action: 'archive',
  },
  {
    id: 'role.view',
    module: 'authorization',
    resource: 'role',
    action: 'view',
    entry: true,
  },
  {
    id: 'role.create',
    module: 'authorization',
    resource: 'role',
    action: 'create',
  },
  {
    id: 'role.update',
    module: 'authorization',
    resource: 'role',
    action: 'update',
  },
  {
    id: 'role.delete',
    module: 'authorization',
    resource: 'role',
    action: 'delete',
  },
  {
    id: 'leave.view',
    module: 'leave',
    resource: 'leave',
    action: 'view',
    entry: true,
  },
  {
    id: 'leave.request',
    module: 'leave',
    resource: 'leave',
    action: 'request',
  },
  {
    id: 'leave.approve',
    module: 'leave',
    resource: 'leave',
    action: 'approve',
  },
  {
    id: 'payroll.view',
    module: 'payroll',
    resource: 'payroll',
    action: 'view',
    entry: true,
  },
  {
    id: 'payroll.run',
    module: 'payroll',
    resource: 'payroll',
    action: 'run',
  },
] as const;
