import * as fs from 'fs';
import * as path from 'path';

import * as yaml from 'js-yaml';

interface RawCatalog {
  permissions: Array<{
    id: string;
    module: string;
    resource: string;
    action: string;
    entry?: boolean;
    deprecated?: boolean;
  }>;
}

function run(): void {
  const yamlPath = path.resolve(
    __dirname,
    '../src/modules/permissions/config/permission-catalog.yaml',
  );
  if (!fs.existsSync(yamlPath)) {
    throw new Error(`Catalog YAML not found at ${yamlPath}`);
  }

  const content = fs.readFileSync(yamlPath, 'utf8');
  const catalog = yaml.load(content) as RawCatalog;

  const codes = catalog.permissions.map((p) => p.id);
  const distinctModules = Array.from(new Set(catalog.permissions.map((p) => p.module)));
  const formattedModules = `[\n${distinctModules.map((m) => `  '${m}',`).join('\n')}\n]`;

  const tsContent = `/**
 * AUTOGENERATED PERMISSION CONTRACTS - DO NOT EDIT MANUALLY
 * Generated from permission-catalog.yaml
 */

export const PermissionCodes = {
${codes.map((code) => `  ${code.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}: '${code}',`).join('\n')}
} as const;

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes];

export const PlatformModules = ${formattedModules} as const;
export type PlatformModule = (typeof PlatformModules)[number];

export interface PermissionMetadata {
  readonly id: PermissionCode;
  readonly module: PlatformModule;
  readonly resource: string;
  readonly action: string;
  readonly entry?: boolean;
  readonly deprecated?: boolean;
}

export const PERMISSION_METADATA_LIST: readonly PermissionMetadata[] = ${JSON.stringify(
    catalog.permissions.map((p) => ({
      id: p.id,
      module: p.module,
      resource: p.resource,
      action: p.action,
      entry: p.entry === true ? true : undefined,
      deprecated: p.deprecated === true ? true : undefined,
    })),
    null,
    2,
  )} as const;
`;

  const outputPath = path.resolve(
    __dirname,
    '../src/modules/permissions/constants/generated-permission-contracts.ts',
  );
  fs.writeFileSync(outputPath, tsContent, 'utf8');

  const contractPath = path.resolve(
    __dirname,
    '../specs/015-permission-catalog/contracts/permission-catalog.contract.ts',
  );
  if (fs.existsSync(contractPath)) {
    const existingContract = fs.readFileSync(contractPath, 'utf8');
    const updatedContract = existingContract.replace(
      /export const PlatformModules = [\s\S]*? as const;/,
      `export const PlatformModules = ${formattedModules} as const;`,
    );
    fs.writeFileSync(contractPath, updatedContract, 'utf8');
  }
}

run();
